window.__AUTH_CONFIG__ = {
  localHosts: ['localhost', '127.0.0.1'],
  trustedAppOrigins: [
    'https://dashboard.continental-hub.com',
    'https://grimoire.continental-hub.com',
    'https://login.continental-hub.com',
    'https://pclaystation.github.io',
    'https://mpmc.ddns.net',
  ],
  trustedApiOrigins: [
    'https://dashboard.continental-hub.com',
    'https://grimoire.continental-hub.com',
    'https://login.continental-hub.com',
    'https://continental-hub.com',
    'https://api.continental-hub.com',
    'https://auth.continental-hub.com',
    'https://id.continental-hub.com',
    'https://backend.continental-hub.com',
    'https://mpmc.ddns.net',
  ],
  preferredApiOrigins: [
    'https://api.continental-hub.com',
    'https://auth.continental-hub.com',
    'https://id.continental-hub.com',
    'https://backend.continental-hub.com',
    'https://continental-hub.com',
    'https://login.continental-hub.com',
  ],
  defaultDashboardOrigin: 'https://dashboard.continental-hub.com',
  hostedApiBaseUrl: 'https://mpmc.ddns.net',
};
